apiVersion: apps/v1 
kind: Deployment
metadata:
  name: go
spec:
  selector:
    matchLabels:
      app: go
  replicas: 2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: go
    spec:
      containers:
      - name: go    #name registred to consul services   
        image: nour963/hello-go   
        ports:
          - containerPort: 8080             
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    worker_processes 1;

    events { worker_connections 1024; }

    http {
    include /etc/nginx/mime.types;

    upstream go {
    server localhost:8080;
    }

    server {

      listen        8000;
      server_name localhost;
      
      location / {
        proxy_read_timeout 300s;
        proxy_connect_timeout 75s;
        proxy_request_buffering off;
        proxy_buffering off;
        proxy_pass  http://go/go.html;

      }

      error_page   500 502 503 504  /50x.html;
      
        location = /50x.html {
            root   /usr/share/nginx/html;
                            }
          } 
        }

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "go:8080" #this port listener is local to nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx       
        image: nour963/nginx-go
        ports:
          - containerPort: 8000 
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-conf  
---

apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: nginx
  
