apiVersion: v1
kind: ConfigMap
metadata:
  name: php-conf
data:
    index.php: |
      <?php
      $servername = "127.0.0.1";
      $username = "nour";
      $password = "hello123";
      
      try {
        $conn = new PDO("mysql:host=$servername;port=3306;dbname=test", $username, $password);
        $conn->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        readfile("yes.html");
          }
      
      catch(PDOException $e)
          {
          readfile("no.html");
          echo "<h3 style=\"color:#f71818; text-align:center; font-size: 150%;\";> ERROR: " . $e->getMessage() ."</h3>";
      
          }
      ?> 

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "mysql:3306"
      labels:
        app: php
    spec:
      containers:
      - name: php
        image: nour963/robot-php
        ports:
          - containerPort: 9000
        volumeMounts:
          - name: php-conf
            mountPath: /var/www/html/index.php
            subPath: index.php
      volumes:
        - name: php-conf
          configMap:
            name: php-conf      
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apache-conf
data:
    apache.conf: |
      ServerName localhost

      LoadModule deflate_module /usr/local/apache2/modules/mod_deflate.so
      LoadModule proxy_module /usr/local/apache2/modules/mod_proxy.so
      LoadModule proxy_fcgi_module /usr/local/apache2/modules/mod_proxy_fcgi.so
      
      <VirtualHost *:80>
          # Proxy .php requests to port 9000 of the php-fpm container
          ProxyPass /http_errors/ !
          ProxyPassMatch ^/(.*\.php(/.*)?)$ fcgi://localhost:9000/var/www/html/$1
          DocumentRoot /var/www/html/
          <Directory /var/www/html/>
              DirectoryIndex index.php
              Options Indexes FollowSymLinks
              AllowOverride All
              Require all granted
          </Directory>
          
          # Send apache logs to stdout and stderr
          Alias /http_errors/ /var/www/html/
          ErrorDocument 503 /http_errors/50x.html
          ErrorDocument 502 /http_errors/50x.html
      </VirtualHost>

---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: apache
spec:
  selector:
    matchLabels:
      app: apache
  replicas: 2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
        "consul.hashicorp.com/connect-service-upstreams": "php:9000"
      labels:
        app: apache
    spec:
      containers:
      - name: apache       
        image: nour963/robot-httpd
        ports:
          - containerPort: 80
        volumeMounts:
        - name: apache-conf
          mountPath: /usr/local/apache2/conf/apache.conf
          subPath: apache.conf
      volumes:
        - name: apache-conf
          configMap:
            name: apache-conf  
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 2
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql      
        image: nour963/robot-mysql
        ports:
        - containerPort: 3306         
   
---
apiVersion: v1
kind: Service
metadata:
  name: apache
  labels:
    app: apache
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: apache
---
